blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Robot-Friends-Community/baggage-claim/discussions
    about: Ask questions or discuss ideas in Discussions
